---
- name: Configure Dashboards
  hosts: dashboard
  become: true

  tasks:
    - name: Setup The Kiosk User
      ansible.builtin.user:
        name: kiosk
        groups:
          - tty
          - input
          - video
          - plugdev
          - audio
        shell: /bin/bash
        append: yes
        state: present

    - name: Add startx Command to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/kiosk/.bashrc"
        line: "[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx -- -nocursor"
        state: present

    - name: Install Required Packages
      apt:
        name:
          - xserver-xorg
          - x11-xserver-utils
          - xinit
          - openbox
          - chromium-browser
          - xinput
        state: present

    - name: Set XDG Configuration
      ansible.builtin.copy:
        content: |
          {% if invert_display is defined and invert_display %}
          xrandr -display :0.0 --output DSI-1 --rotate inverted
          xinput --set-prop 6 'Coordinate Transformation Matrix' -1 0 1 0 -1 1 0 0 1
          {% endif %}
          sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' /home/kiosk/.config/chromium/Default/Preferences
          sed -i 's/"exit_type":"Crashed"/"exit_type":"Normal"/' /home/kiosk/.config/chromium/Default/Preferences
          xset -dpms
          xset s noblank
          xset s off
          chromium-browser \
              --kiosk \
              --noerrdialogs \
              --disable-infobars \
              --disable-pinch \
              --enable-features=OverlayScrollbar \
              'https://homeassistant.hyde.services/'
        dest: /etc/xdg/openbox/autostart

    - name: Download Dimmer Binary
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/hydazz/ansible/main/files/dimmer"
        dest: "/usr/local/bin/dimmer"
        mode: "0755"
        owner: "root"

    - name: Find Event For Touchscreen
      ansible.builtin.shell:
        cmd: grep -A5 'generic ft5x06' /proc/bus/input/devices | grep -Eo 'event[0-9]+'
      register: touchscreen_event

    - name: Setup Dimmer Service
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Dimmer Service
          After=backlight.target

          [Service]
          ExecStartPre=/bin/bash -c '[ -e /sys/class/backlight/10-0045/brightness ] && echo 255 | tee /sys/class/backlight/10-0045/brightness'
          ExecStart=/usr/local/bin/dimmer 10 15 {{ touchscreen_event.stdout }}
          ExecStop=/bin/bash -c 'echo 255 | tee /sys/class/backlight/10-0045/brightness'
          ExecStopPost=/bin/bash -c 'echo 255 | tee /sys/class/backlight/10-0045/brightness'
          Restart=on-failure
          RestartSec=5s

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/dimmer.service"
      notify: daemon-reload

    - name: Make Dimmer Service Start At Boot
      ansible.builtin.systemd:
        name: dimmer
        state: started
        enabled: yes

    - name: Allow Anybody To Use X11
      ansible.builtin.copy:
        content: |
          allowed_users=anybody
          needs_root_rights=yes
        dest: "/etc/X11/Xwrapper.config"

    - name: Setup Console Auto Login
      ansible.builtin.copy:
        content: |
          [Service]
          ExecStart=
          ExecStart=-/sbin/agetty --autologin kiosk --noclear %I $TERM
        dest: "/etc/systemd/system/getty@tty1.service.d/autologin.conf"

  handlers:
    - name: daemon-reload
      ansible.builtin.systemd:
        daemon_reload: yes
